/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface LeaderboardEntry {
    principal: Principal;
    displayName: string;
    digiPointsReward: bigint;
}
export interface BankAccount {
    id: string;
    balance: number;
    userId: string;
    createdAt: Time;
    bankName: string;
    accountType: string;
    accountNumber: string;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Feedback {
    id: bigint;
    submittedBy: Principal;
    message: string;
    timestamp: Time;
    rating: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Transaction {
    id: string;
    merchantName: string;
    transactionType: TransactionType;
    bankAccountId: string;
    userId: string;
    date: Time;
    createdAt: Time;
    category: TransactionCategory;
    amount: number;
}
export interface Challenge {
    id: string;
    durationDays: bigint;
    title: string;
    description: string;
    targetAmount: number;
    digiPointsReward: bigint;
    category: TransactionCategory;
}
export interface UserProfile {
    referralCode: string;
    colorMode: ColorMode;
    displayName: string;
    name: string;
    createdAt: Time;
    isAnonymous: boolean;
    email: string;
    avatarUrl: string;
    digiPointsReward: bigint;
    walletBalance: bigint;
}
export interface SupportTicket {
    id: bigint;
    subject: string;
    description: string;
    timestamp: Time;
    raisedBy: Principal;
}
export enum ColorMode {
    dark = "dark",
    light = "light"
}
export enum TransactionCategory {
    transportation = "transportation",
    clothing = "clothing",
    other = "other",
    entertainment = "entertainment",
    food = "food",
    travel = "travel",
    utilities = "utilities",
    groceries = "groceries",
    shopping = "shopping",
    college = "college",
    health = "health"
}
export enum TransactionType {
    credit = "credit",
    debit = "debit"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBankAccount(account: BankAccount): Promise<void>;
    addChallenge(challenge: Challenge): Promise<void>;
    addTransaction(transaction: Transaction): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkBalance(arg0: string): Promise<number>;
    getAllFeedback(): Promise<Array<Feedback>>;
    getAllSupportTickets(): Promise<Array<SupportTicket>>;
    getBankAccounts(): Promise<Array<BankAccount>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChallenges(): Promise<Array<Challenge>>;
    getLeaderboard(): Promise<Array<LeaderboardEntry>>;
    getLeaderboardEntry(user: Principal): Promise<{
        displayName: string;
        digiPointsReward: bigint;
    } | null>;
    getTransactions(): Promise<Array<Transaction>>;
    getTransactionsByCategory(category: TransactionCategory): Promise<Array<Transaction>>;
    getTransactionsByDateRange(startDate: Time, endDate: Time): Promise<Array<Transaction>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    removeBankAccount(accountId: string): Promise<void>;
    removeChallenge(id: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    seedDemoData(): Promise<void>;
    sendMoney(arg0: bigint): Promise<void>;
    submitFeedback(rating: bigint, message: string): Promise<void>;
    submitSupportTicket(subject: string, description: string): Promise<void>;
    updateBalance(accountId: string, newBalance: number): Promise<void>;
    updateLeaderboardPreferences(displayName: string, isAnonymous: boolean): Promise<void>;
}
import type { Challenge as _Challenge, ColorMode as _ColorMode, Time as _Time, Transaction as _Transaction, TransactionCategory as _TransactionCategory, TransactionType as _TransactionType, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBankAccount(arg0: BankAccount): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBankAccount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBankAccount(arg0);
            return result;
        }
    }
    async addChallenge(arg0: Challenge): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addChallenge(to_candid_Challenge_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addChallenge(to_candid_Challenge_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addTransaction(arg0: Transaction): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransaction(to_candid_Transaction_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransaction(to_candid_Transaction_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkBalance(arg0: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.checkBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkBalance(arg0);
            return result;
        }
    }
    async getAllFeedback(): Promise<Array<Feedback>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFeedback();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFeedback();
            return result;
        }
    }
    async getAllSupportTickets(): Promise<Array<SupportTicket>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSupportTickets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSupportTickets();
            return result;
        }
    }
    async getBankAccounts(): Promise<Array<BankAccount>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBankAccounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBankAccounts();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChallenges(): Promise<Array<Challenge>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChallenges();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChallenges();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaderboard(): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return result;
        }
    }
    async getLeaderboardEntry(arg0: Principal): Promise<{
        displayName: string;
        digiPointsReward: bigint;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboardEntry(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboardEntry(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactions();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactions();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactionsByCategory(arg0: TransactionCategory): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionsByCategory(to_candid_TransactionCategory_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionsByCategory(to_candid_TransactionCategory_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactionsByDateRange(arg0: Time, arg1: Time): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionsByDateRange(arg0, arg1);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionsByDateRange(arg0, arg1);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async removeBankAccount(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeBankAccount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeBankAccount(arg0);
            return result;
        }
    }
    async removeChallenge(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeChallenge(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeChallenge(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n36(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n36(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async seedDemoData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedDemoData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedDemoData();
            return result;
        }
    }
    async sendMoney(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMoney(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMoney(arg0);
            return result;
        }
    }
    async submitFeedback(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitFeedback(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitFeedback(arg0, arg1);
            return result;
        }
    }
    async submitSupportTicket(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitSupportTicket(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitSupportTicket(arg0, arg1);
            return result;
        }
    }
    async updateBalance(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBalance(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBalance(arg0, arg1);
            return result;
        }
    }
    async updateLeaderboardPreferences(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLeaderboardPreferences(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLeaderboardPreferences(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Challenge_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Challenge): Challenge {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_ColorMode_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ColorMode): ColorMode {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionCategory_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionCategory): TransactionCategory {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        displayName: string;
        digiPointsReward: bigint;
    }]): {
    displayName: string;
    digiPointsReward: bigint;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    referralCode: string;
    colorMode: _ColorMode;
    displayName: string;
    name: string;
    createdAt: _Time;
    isAnonymous: boolean;
    email: string;
    avatarUrl: string;
    digiPointsReward: bigint;
    walletBalance: bigint;
}): {
    referralCode: string;
    colorMode: ColorMode;
    displayName: string;
    name: string;
    createdAt: Time;
    isAnonymous: boolean;
    email: string;
    avatarUrl: string;
    digiPointsReward: bigint;
    walletBalance: bigint;
} {
    return {
        referralCode: value.referralCode,
        colorMode: from_candid_ColorMode_n21(_uploadFile, _downloadFile, value.colorMode),
        displayName: value.displayName,
        name: value.name,
        createdAt: value.createdAt,
        isAnonymous: value.isAnonymous,
        email: value.email,
        avatarUrl: value.avatarUrl,
        digiPointsReward: value.digiPointsReward,
        walletBalance: value.walletBalance
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    durationDays: bigint;
    title: string;
    description: string;
    targetAmount: number;
    digiPointsReward: bigint;
    category: _TransactionCategory;
}): {
    id: string;
    durationDays: bigint;
    title: string;
    description: string;
    targetAmount: number;
    digiPointsReward: bigint;
    category: TransactionCategory;
} {
    return {
        id: value.id,
        durationDays: value.durationDays,
        title: value.title,
        description: value.description,
        targetAmount: value.targetAmount,
        digiPointsReward: value.digiPointsReward,
        category: from_candid_TransactionCategory_n28(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    merchantName: string;
    transactionType: _TransactionType;
    bankAccountId: string;
    userId: string;
    date: _Time;
    createdAt: _Time;
    category: _TransactionCategory;
    amount: number;
}): {
    id: string;
    merchantName: string;
    transactionType: TransactionType;
    bankAccountId: string;
    userId: string;
    date: Time;
    createdAt: Time;
    category: TransactionCategory;
    amount: number;
} {
    return {
        id: value.id,
        merchantName: value.merchantName,
        transactionType: from_candid_TransactionType_n34(_uploadFile, _downloadFile, value.transactionType),
        bankAccountId: value.bankAccountId,
        userId: value.userId,
        date: value.date,
        createdAt: value.createdAt,
        category: from_candid_TransactionCategory_n28(_uploadFile, _downloadFile, value.category),
        amount: value.amount
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dark: null;
} | {
    light: null;
}): ColorMode {
    return "dark" in value ? ColorMode.dark : "light" in value ? ColorMode.light : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    transportation: null;
} | {
    clothing: null;
} | {
    other: null;
} | {
    entertainment: null;
} | {
    food: null;
} | {
    travel: null;
} | {
    utilities: null;
} | {
    groceries: null;
} | {
    shopping: null;
} | {
    college: null;
} | {
    health: null;
}): TransactionCategory {
    return "transportation" in value ? TransactionCategory.transportation : "clothing" in value ? TransactionCategory.clothing : "other" in value ? TransactionCategory.other : "entertainment" in value ? TransactionCategory.entertainment : "food" in value ? TransactionCategory.food : "travel" in value ? TransactionCategory.travel : "utilities" in value ? TransactionCategory.utilities : "groceries" in value ? TransactionCategory.groceries : "shopping" in value ? TransactionCategory.shopping : "college" in value ? TransactionCategory.college : "health" in value ? TransactionCategory.health : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    credit: null;
} | {
    debit: null;
}): TransactionType {
    return "credit" in value ? TransactionType.credit : "debit" in value ? TransactionType.debit : value;
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Challenge>): Array<Challenge> {
    return value.map((x)=>from_candid_Challenge_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n32(_uploadFile, _downloadFile, x));
}
function to_candid_Challenge_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Challenge): _Challenge {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_ColorMode_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ColorMode): _ColorMode {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionCategory_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionCategory): _TransactionCategory {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): _TransactionType {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_Transaction_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Transaction): _Transaction {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    merchantName: string;
    transactionType: TransactionType;
    bankAccountId: string;
    userId: string;
    date: Time;
    createdAt: Time;
    category: TransactionCategory;
    amount: number;
}): {
    id: string;
    merchantName: string;
    transactionType: _TransactionType;
    bankAccountId: string;
    userId: string;
    date: _Time;
    createdAt: _Time;
    category: _TransactionCategory;
    amount: number;
} {
    return {
        id: value.id,
        merchantName: value.merchantName,
        transactionType: to_candid_TransactionType_n14(_uploadFile, _downloadFile, value.transactionType),
        bankAccountId: value.bankAccountId,
        userId: value.userId,
        date: value.date,
        createdAt: value.createdAt,
        category: to_candid_TransactionCategory_n10(_uploadFile, _downloadFile, value.category),
        amount: value.amount
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    referralCode: string;
    colorMode: ColorMode;
    displayName: string;
    name: string;
    createdAt: Time;
    isAnonymous: boolean;
    email: string;
    avatarUrl: string;
    digiPointsReward: bigint;
    walletBalance: bigint;
}): {
    referralCode: string;
    colorMode: _ColorMode;
    displayName: string;
    name: string;
    createdAt: _Time;
    isAnonymous: boolean;
    email: string;
    avatarUrl: string;
    digiPointsReward: bigint;
    walletBalance: bigint;
} {
    return {
        referralCode: value.referralCode,
        colorMode: to_candid_ColorMode_n38(_uploadFile, _downloadFile, value.colorMode),
        displayName: value.displayName,
        name: value.name,
        createdAt: value.createdAt,
        isAnonymous: value.isAnonymous,
        email: value.email,
        avatarUrl: value.avatarUrl,
        digiPointsReward: value.digiPointsReward,
        walletBalance: value.walletBalance
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    durationDays: bigint;
    title: string;
    description: string;
    targetAmount: number;
    digiPointsReward: bigint;
    category: TransactionCategory;
}): {
    id: string;
    durationDays: bigint;
    title: string;
    description: string;
    targetAmount: number;
    digiPointsReward: bigint;
    category: _TransactionCategory;
} {
    return {
        id: value.id,
        durationDays: value.durationDays,
        title: value.title,
        description: value.description,
        targetAmount: value.targetAmount,
        digiPointsReward: value.digiPointsReward,
        category: to_candid_TransactionCategory_n10(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionCategory): {
    transportation: null;
} | {
    clothing: null;
} | {
    other: null;
} | {
    entertainment: null;
} | {
    food: null;
} | {
    travel: null;
} | {
    utilities: null;
} | {
    groceries: null;
} | {
    shopping: null;
} | {
    college: null;
} | {
    health: null;
} {
    return value == TransactionCategory.transportation ? {
        transportation: null
    } : value == TransactionCategory.clothing ? {
        clothing: null
    } : value == TransactionCategory.other ? {
        other: null
    } : value == TransactionCategory.entertainment ? {
        entertainment: null
    } : value == TransactionCategory.food ? {
        food: null
    } : value == TransactionCategory.travel ? {
        travel: null
    } : value == TransactionCategory.utilities ? {
        utilities: null
    } : value == TransactionCategory.groceries ? {
        groceries: null
    } : value == TransactionCategory.shopping ? {
        shopping: null
    } : value == TransactionCategory.college ? {
        college: null
    } : value == TransactionCategory.health ? {
        health: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): {
    credit: null;
} | {
    debit: null;
} {
    return value == TransactionType.credit ? {
        credit: null
    } : value == TransactionType.debit ? {
        debit: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ColorMode): {
    dark: null;
} | {
    light: null;
} {
    return value == ColorMode.dark ? {
        dark: null
    } : value == ColorMode.light ? {
        light: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
