/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BankAccount {
  'id' : string,
  'balance' : number,
  'userId' : string,
  'createdAt' : Time,
  'bankName' : string,
  'accountType' : string,
  'accountNumber' : string,
}
export interface Challenge {
  'id' : string,
  'durationDays' : bigint,
  'title' : string,
  'description' : string,
  'targetAmount' : number,
  'digiPointsReward' : bigint,
  'category' : TransactionCategory,
}
export type ColorMode = { 'dark' : null } |
  { 'light' : null };
export interface Feedback {
  'id' : bigint,
  'submittedBy' : Principal,
  'message' : string,
  'timestamp' : Time,
  'rating' : bigint,
}
export interface LeaderboardEntry {
  'principal' : Principal,
  'displayName' : string,
  'digiPointsReward' : bigint,
}
export interface SupportTicket {
  'id' : bigint,
  'subject' : string,
  'description' : string,
  'timestamp' : Time,
  'raisedBy' : Principal,
}
export type Time = bigint;
export interface Transaction {
  'id' : string,
  'merchantName' : string,
  'transactionType' : TransactionType,
  'bankAccountId' : string,
  'userId' : string,
  'date' : Time,
  'createdAt' : Time,
  'category' : TransactionCategory,
  'amount' : number,
}
export type TransactionCategory = { 'transportation' : null } |
  { 'clothing' : null } |
  { 'other' : null } |
  { 'entertainment' : null } |
  { 'food' : null } |
  { 'travel' : null } |
  { 'utilities' : null } |
  { 'groceries' : null } |
  { 'shopping' : null } |
  { 'college' : null } |
  { 'health' : null };
export type TransactionType = { 'credit' : null } |
  { 'debit' : null };
export interface UserProfile {
  'referralCode' : string,
  'colorMode' : ColorMode,
  'displayName' : string,
  'name' : string,
  'createdAt' : Time,
  'isAnonymous' : boolean,
  'email' : string,
  'avatarUrl' : string,
  'digiPointsReward' : bigint,
  'walletBalance' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBankAccount' : ActorMethod<[BankAccount], undefined>,
  'addChallenge' : ActorMethod<[Challenge], undefined>,
  'addTransaction' : ActorMethod<[Transaction], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkBalance' : ActorMethod<[string], number>,
  'getAllFeedback' : ActorMethod<[], Array<Feedback>>,
  'getAllSupportTickets' : ActorMethod<[], Array<SupportTicket>>,
  'getBankAccounts' : ActorMethod<[], Array<BankAccount>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChallenges' : ActorMethod<[], Array<Challenge>>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getLeaderboardEntry' : ActorMethod<
    [Principal],
    [] | [{ 'displayName' : string, 'digiPointsReward' : bigint }]
  >,
  'getTransactions' : ActorMethod<[], Array<Transaction>>,
  'getTransactionsByCategory' : ActorMethod<
    [TransactionCategory],
    Array<Transaction>
  >,
  'getTransactionsByDateRange' : ActorMethod<[Time, Time], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeBankAccount' : ActorMethod<[string], undefined>,
  'removeChallenge' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedDemoData' : ActorMethod<[], undefined>,
  'sendMoney' : ActorMethod<[bigint], undefined>,
  'submitFeedback' : ActorMethod<[bigint, string], undefined>,
  'submitSupportTicket' : ActorMethod<[string, string], undefined>,
  'updateBalance' : ActorMethod<[string, number], undefined>,
  'updateLeaderboardPreferences' : ActorMethod<[string, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];