/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const BankAccount = IDL.Record({
  'id' : IDL.Text,
  'balance' : IDL.Float64,
  'userId' : IDL.Text,
  'createdAt' : Time,
  'bankName' : IDL.Text,
  'accountType' : IDL.Text,
  'accountNumber' : IDL.Text,
});
export const TransactionCategory = IDL.Variant({
  'transportation' : IDL.Null,
  'clothing' : IDL.Null,
  'other' : IDL.Null,
  'entertainment' : IDL.Null,
  'food' : IDL.Null,
  'travel' : IDL.Null,
  'utilities' : IDL.Null,
  'groceries' : IDL.Null,
  'shopping' : IDL.Null,
  'college' : IDL.Null,
  'health' : IDL.Null,
});
export const Challenge = IDL.Record({
  'id' : IDL.Text,
  'durationDays' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'targetAmount' : IDL.Float64,
  'digiPointsReward' : IDL.Nat,
  'category' : TransactionCategory,
});
export const TransactionType = IDL.Variant({
  'credit' : IDL.Null,
  'debit' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'merchantName' : IDL.Text,
  'transactionType' : TransactionType,
  'bankAccountId' : IDL.Text,
  'userId' : IDL.Text,
  'date' : Time,
  'createdAt' : Time,
  'category' : TransactionCategory,
  'amount' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Feedback = IDL.Record({
  'id' : IDL.Nat,
  'submittedBy' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : Time,
  'rating' : IDL.Nat,
});
export const SupportTicket = IDL.Record({
  'id' : IDL.Nat,
  'subject' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : Time,
  'raisedBy' : IDL.Principal,
});
export const ColorMode = IDL.Variant({ 'dark' : IDL.Null, 'light' : IDL.Null });
export const UserProfile = IDL.Record({
  'referralCode' : IDL.Text,
  'colorMode' : ColorMode,
  'displayName' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'isAnonymous' : IDL.Bool,
  'email' : IDL.Text,
  'avatarUrl' : IDL.Text,
  'digiPointsReward' : IDL.Nat,
  'walletBalance' : IDL.Nat,
});
export const LeaderboardEntry = IDL.Record({
  'principal' : IDL.Principal,
  'displayName' : IDL.Text,
  'digiPointsReward' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBankAccount' : IDL.Func([BankAccount], [], []),
  'addChallenge' : IDL.Func([Challenge], [], []),
  'addTransaction' : IDL.Func([Transaction], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkBalance' : IDL.Func([IDL.Text], [IDL.Float64], []),
  'getAllFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
  'getAllSupportTickets' : IDL.Func([], [IDL.Vec(SupportTicket)], ['query']),
  'getBankAccounts' : IDL.Func([], [IDL.Vec(BankAccount)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChallenges' : IDL.Func([], [IDL.Vec(Challenge)], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getLeaderboardEntry' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Opt(
          IDL.Record({ 'displayName' : IDL.Text, 'digiPointsReward' : IDL.Nat })
        ),
      ],
      ['query'],
    ),
  'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getTransactionsByCategory' : IDL.Func(
      [TransactionCategory],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getTransactionsByDateRange' : IDL.Func(
      [Time, Time],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeBankAccount' : IDL.Func([IDL.Text], [], []),
  'removeChallenge' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedDemoData' : IDL.Func([], [], []),
  'sendMoney' : IDL.Func([IDL.Nat], [], []),
  'submitFeedback' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'submitSupportTicket' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateBalance' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'updateLeaderboardPreferences' : IDL.Func([IDL.Text, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const BankAccount = IDL.Record({
    'id' : IDL.Text,
    'balance' : IDL.Float64,
    'userId' : IDL.Text,
    'createdAt' : Time,
    'bankName' : IDL.Text,
    'accountType' : IDL.Text,
    'accountNumber' : IDL.Text,
  });
  const TransactionCategory = IDL.Variant({
    'transportation' : IDL.Null,
    'clothing' : IDL.Null,
    'other' : IDL.Null,
    'entertainment' : IDL.Null,
    'food' : IDL.Null,
    'travel' : IDL.Null,
    'utilities' : IDL.Null,
    'groceries' : IDL.Null,
    'shopping' : IDL.Null,
    'college' : IDL.Null,
    'health' : IDL.Null,
  });
  const Challenge = IDL.Record({
    'id' : IDL.Text,
    'durationDays' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'targetAmount' : IDL.Float64,
    'digiPointsReward' : IDL.Nat,
    'category' : TransactionCategory,
  });
  const TransactionType = IDL.Variant({
    'credit' : IDL.Null,
    'debit' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'merchantName' : IDL.Text,
    'transactionType' : TransactionType,
    'bankAccountId' : IDL.Text,
    'userId' : IDL.Text,
    'date' : Time,
    'createdAt' : Time,
    'category' : TransactionCategory,
    'amount' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Feedback = IDL.Record({
    'id' : IDL.Nat,
    'submittedBy' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : Time,
    'rating' : IDL.Nat,
  });
  const SupportTicket = IDL.Record({
    'id' : IDL.Nat,
    'subject' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : Time,
    'raisedBy' : IDL.Principal,
  });
  const ColorMode = IDL.Variant({ 'dark' : IDL.Null, 'light' : IDL.Null });
  const UserProfile = IDL.Record({
    'referralCode' : IDL.Text,
    'colorMode' : ColorMode,
    'displayName' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'isAnonymous' : IDL.Bool,
    'email' : IDL.Text,
    'avatarUrl' : IDL.Text,
    'digiPointsReward' : IDL.Nat,
    'walletBalance' : IDL.Nat,
  });
  const LeaderboardEntry = IDL.Record({
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
    'digiPointsReward' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBankAccount' : IDL.Func([BankAccount], [], []),
    'addChallenge' : IDL.Func([Challenge], [], []),
    'addTransaction' : IDL.Func([Transaction], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkBalance' : IDL.Func([IDL.Text], [IDL.Float64], []),
    'getAllFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
    'getAllSupportTickets' : IDL.Func([], [IDL.Vec(SupportTicket)], ['query']),
    'getBankAccounts' : IDL.Func([], [IDL.Vec(BankAccount)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChallenges' : IDL.Func([], [IDL.Vec(Challenge)], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getLeaderboardEntry' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Opt(
            IDL.Record({
              'displayName' : IDL.Text,
              'digiPointsReward' : IDL.Nat,
            })
          ),
        ],
        ['query'],
      ),
    'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getTransactionsByCategory' : IDL.Func(
        [TransactionCategory],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getTransactionsByDateRange' : IDL.Func(
        [Time, Time],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeBankAccount' : IDL.Func([IDL.Text], [], []),
    'removeChallenge' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedDemoData' : IDL.Func([], [], []),
    'sendMoney' : IDL.Func([IDL.Nat], [], []),
    'submitFeedback' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'submitSupportTicket' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateBalance' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'updateLeaderboardPreferences' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };